### ISSUE TITLE
Add datasets

### ISSUE THREAD

**Issue by dankeemahill** [danhillreports/aaja-diy-mapping#1]
- [ ] Different geography scale/different geometries (point, polygon...)

**Comment by jueyang** [comment]
Hey @danhillreports, I'll add some materials tomorrow. Be in SF from Wednesday on. Let's scheme before the conf.

**Comment by jueyang** [comment]
Added a few datasets in `starter.md`. So far I'm trying to find things that focus on SF (figured it'd might be more relevant to the conf.)

Can you add a few more that you think might be interesting?
