### ISSUE TITLE
Links to examples

### ISSUE THREAD

**Issue by dankeemahill** [danhillreports/aaja-diy-mapping#3]

**Comment by jueyang** [comment]
I posted talking points in [`intro.md`](https://github.com/danhillreports/aaja-diy-mapping/blob/master/intro.md), including examples.
- `starter.md`: for the workshop portion, including setup sample datasets
- `next.md`: actions to take after the workshop

Can you give them a read and add/edit where you see fit? I'll turn `intro.md` into slides later.
